### ISSUE TITLE
Set a custom remote repo URL

### ISSUE THREAD

**Issue by davidpmccormick** [josa42/atom-blame#8]
Are there any plans to implement linking to remote repos that aren't GitHub/BitBucket?

**Comment by josa42** [comment]
@davidpmccormick I thought about it. But I couldn't come up with a good solution. Because the setting would have to be per-project not global, which is not supported by atom for now. 

Right now if the remote matches `git@{host}:{user}/{repo}.git`, `https://{username}@{host}/{user}/{repo}` or `https://{host}/{user}/{repo}` it links to `https://{host}/{user}/{repo}/commit/{hash}`, which should cover most cases.

But I have only tested GitHub, Bitbucket and GitLab. For which remote URL is it not working for you?

**Comment by pabra** [comment]
I just saw this feature request. Maybe my [pull request](https://github.com/josa42/atom-blame/pull/10) is what @davidpmccormick asked for.

**Comment by josa42** [comment]
Resolved by #12
